// <auto-generated />
using System;
using Intex_Remix.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intex_Remix.Migrations
{
    [DbContext(typeof(MummyDBContext))]
    partial class MummyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intex_Remix.Models.Bio", b =>
                {
                    b.Property<string>("Bag")
                        .HasColumnName("bag_#")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialId")
                        .HasColumnName("burial_ID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationEw")
                        .HasColumnName("burial_location_EW")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationNs")
                        .HasColumnName("burial_location_NS")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialNumber")
                        .HasColumnName("burial_number")
                        .HasColumnType("float");

                    b.Property<string>("BurialSubplot")
                        .HasColumnName("burial_subplot")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Cluster")
                        .HasColumnName("cluster_#")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Date")
                        .HasColumnName("date")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Initials")
                        .HasColumnName("initials")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("LowPairEw")
                        .HasColumnName("low_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairNs")
                        .HasColumnName("low_pair_NS")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PreviouslySampled")
                        .HasColumnName("previously_sampled")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Rack")
                        .HasColumnName("rack_#")
                        .HasColumnType("float");

                    b.ToTable("Bio$");
                });

            modelBuilder.Entity("Intex_Remix.Models.Carbon", b =>
                {
                    b.Property<string>("Area")
                        .HasColumnName("area")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialId")
                        .HasColumnName("burial_ID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationEw")
                        .HasColumnName("burial_location_EW")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationNs")
                        .HasColumnName("burial_location_NS")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialNumber")
                        .HasColumnName("burial_number")
                        .HasColumnType("float");

                    b.Property<string>("BurialSubplot")
                        .HasColumnName("burial_subplot")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("C14Sample2017")
                        .HasColumnName("c14_sample_2017")
                        .HasColumnType("float");

                    b.Property<string>("Calibrated95CalendarDateAvg")
                        .HasColumnName("calibrated_95%_calendar_date_avg")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Calibrated95CalendarDateMax")
                        .HasColumnName("calibrated_95%_calendar_date_max")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Calibrated95CalendarDateMin")
                        .HasColumnName("calibrated_95%_calendar_date_min")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Calibrated95CalendarDateSpan")
                        .HasColumnName("calibrated_95%_calendar_date_span")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnName("category")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Conventional14cAgeBp")
                        .HasColumnName("conventional_14c_age_BP")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("F18")
                        .HasColumnType("float");

                    b.Property<string>("F27")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Foci")
                        .HasColumnName("foci")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnName("location")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("LowPairEw")
                        .HasColumnName("low_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairNs")
                        .HasColumnName("low_pair_NS")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Questions")
                        .HasColumnName("questions")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("RackA")
                        .HasColumnName("rack_a")
                        .HasColumnType("float");

                    b.Property<double?>("RackB")
                        .HasColumnName("rack_b")
                        .HasColumnType("float");

                    b.Property<double?>("SizeMl")
                        .HasColumnName("size_(ml)")
                        .HasColumnType("float");

                    b.Property<double?>("TubeNumber")
                        .HasColumnName("tube_number")
                        .HasColumnType("float");

                    b.Property<string>("_14cCalendarDate")
                        .HasColumnName("14c_calendar_date")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.ToTable("Carbon$");
                });

            modelBuilder.Entity("Intex_Remix.Models.Cranial", b =>
                {
                    b.Property<double?>("BasionBregmaHeight")
                        .HasColumnName("basion-bregma_height")
                        .HasColumnType("float");

                    b.Property<double?>("BasionNasion")
                        .HasColumnName("basion-nasion")
                        .HasColumnType("float");

                    b.Property<double?>("BasionProsthionLength")
                        .HasColumnName("basion-prosthion_length")
                        .HasColumnType("float");

                    b.Property<double?>("BizygomaticDiameter")
                        .HasColumnName("bizygomatic_diameter")
                        .HasColumnType("float");

                    b.Property<string>("BodyGender")
                        .HasColumnName("body_gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialArtifactDescription")
                        .HasColumnName("burial/artifact_description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialDepth")
                        .HasColumnName("burial_depth")
                        .HasColumnType("float");

                    b.Property<string>("BurialId")
                        .HasColumnName("burial_ID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationEw")
                        .HasColumnName("burial_location_EW")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationNs")
                        .HasColumnName("burial_location_NS")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialNumber")
                        .HasColumnName("burial_number")
                        .HasColumnType("float");

                    b.Property<string>("BurialSubplot")
                        .HasColumnName("burial_subplot")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("BuriedWithArtifacts")
                        .HasColumnName("buried_with_artifacts")
                        .HasColumnType("bit");

                    b.Property<string>("GilesGender")
                        .HasColumnName("giles_gender")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("InterorbitalBreadth")
                        .HasColumnName("interorbital_breadth")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairEw")
                        .HasColumnName("low_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairNs")
                        .HasColumnName("low_pair_NS")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumCranialBreadth")
                        .HasColumnName("maximum_cranial_breadth")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumCranialLength")
                        .HasColumnName("maximum_cranial_length")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumNasalBreadth")
                        .HasColumnName("maximum_nasal_breadth")
                        .HasColumnType("float");

                    b.Property<double?>("NasionProsthion")
                        .HasColumnName("nasion-prosthion")
                        .HasColumnType("float");

                    b.Property<double?>("SampleNumber")
                        .HasColumnName("sample_number")
                        .HasColumnType("float");

                    b.ToTable("Cranial$");
                });

            modelBuilder.Entity("Intex_Remix.Models.Main", b =>
                {
                    b.Property<string>("BurialId")
                        .HasColumnName("burial_ID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("ArtifactFound")
                        .HasColumnName("artifact_found")
                        .HasColumnType("bit");

                    b.Property<string>("ArtifactsDescription")
                        .HasColumnName("artifacts_description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BasilarSuture")
                        .HasColumnName("basilar_suture")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BasionBregmaHeight")
                        .HasColumnName("basion_bregma_height")
                        .HasColumnType("float");

                    b.Property<double?>("BasionNasion")
                        .HasColumnName("basion_nasion")
                        .HasColumnType("float");

                    b.Property<double?>("BasionProsthionLength")
                        .HasColumnName("basion_prosthion_length")
                        .HasColumnType("float");

                    b.Property<double?>("BizygomaticDiameter")
                        .HasColumnName("bizygomatic_diameter")
                        .HasColumnType("float");

                    b.Property<string>("BoneLength")
                        .HasColumnName("bone_length")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("BoneTaken")
                        .HasColumnName("bone_taken")
                        .HasColumnType("bit");

                    b.Property<double?>("BurialDepth")
                        .HasColumnName("burial_depth")
                        .HasColumnType("float");

                    b.Property<string>("BurialLocationEw")
                        .HasColumnName("burial_location_EW")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationNs")
                        .HasColumnName("burial_location_NS")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialNumber")
                        .HasColumnName("burial_number")
                        .HasColumnType("float");

                    b.Property<string>("BurialSituation")
                        .HasColumnName("burial_situation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BurialSubplot")
                        .HasColumnName("burial_subplot")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CranialSuture")
                        .HasColumnName("cranial_suture")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DayFound")
                        .HasColumnName("day_found")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DescriptionOfTaken")
                        .HasColumnName("description_of_taken")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("DorsalPitting")
                        .HasColumnName("dorsal_pitting")
                        .HasColumnType("float");

                    b.Property<string>("EpiphysealUnion")
                        .HasColumnName("epiphyseal_union")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("EstimateAge")
                        .HasColumnName("estimate_age")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("EstimateLivingStature")
                        .HasColumnName("estimate_living_stature")
                        .HasColumnType("float");

                    b.Property<string>("FemurDiameter")
                        .HasColumnName("femur_diameter")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("FemurHead")
                        .HasColumnName("femur_head")
                        .HasColumnType("float");

                    b.Property<double?>("FemurLength")
                        .HasColumnName("femur_length")
                        .HasColumnType("float");

                    b.Property<string>("ForemanMagnum")
                        .HasColumnName("foreman_magnum")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("GeFunctionTotal")
                        .HasColumnName("GE_function_total")
                        .HasColumnType("float");

                    b.Property<string>("GenderBodyCol")
                        .HasColumnName("gender_body_col")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("GenderGe")
                        .HasColumnName("gender_GE")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Gonian")
                        .HasColumnName("gonian")
                        .HasColumnType("float");

                    b.Property<string>("HairColor")
                        .HasColumnName("hair_color")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("HairTaken")
                        .HasColumnName("hair_taken")
                        .HasColumnType("bit");

                    b.Property<string>("HeadDirection")
                        .HasColumnName("head_direction")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("HighPairEw")
                        .HasColumnName("high_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("HighPairNs")
                        .HasColumnName("high_pair_NS")
                        .HasColumnType("float");

                    b.Property<string>("Humerus")
                        .HasColumnName("humerus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("HumerusHead")
                        .HasColumnName("humerus_head")
                        .HasColumnType("float");

                    b.Property<double?>("HumerusLength")
                        .HasColumnName("humerus_length")
                        .HasColumnType("float");

                    b.Property<string>("IliacCrest")
                        .HasColumnName("iliac_crest")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("InterorbitalBreadth")
                        .HasColumnName("interorbital_breadth")
                        .HasColumnType("float");

                    b.Property<double?>("LengthOfRemains")
                        .HasColumnName("length_of_remains")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairEw")
                        .HasColumnName("low_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairNs")
                        .HasColumnName("low_pair_NS")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumCranialBreadth")
                        .HasColumnName("maximum_cranial_breadth")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumCranialLength")
                        .HasColumnName("maximum_cranial_length")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumNasalBreadth")
                        .HasColumnName("maximum_nasal_breadth")
                        .HasColumnType("float");

                    b.Property<string>("MedialClavicle")
                        .HasColumnName("medial_clavicle")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("MedialIpRamus")
                        .HasColumnName("medial_IP_ramus")
                        .HasColumnType("float");

                    b.Property<string>("MonthFound")
                        .HasColumnName("month_found")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("NasionProsthion")
                        .HasColumnName("nasion_prosthion")
                        .HasColumnType("float");

                    b.Property<double?>("NuchalCrest")
                        .HasColumnName("nuchal_crest")
                        .HasColumnType("float");

                    b.Property<double?>("OrbitEdge")
                        .HasColumnName("orbit_edge")
                        .HasColumnType("float");

                    b.Property<string>("Osteophytosis")
                        .HasColumnName("osteophytosis")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("ParietalBossing")
                        .HasColumnName("parietal_bossing")
                        .HasColumnType("float");

                    b.Property<string>("PathologyAnomalies")
                        .HasColumnName("pathology_anomalies")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("PreaurSulcus")
                        .HasColumnName("preaur_sulcus")
                        .HasColumnType("float");

                    b.Property<string>("PreservationIndex")
                        .HasColumnName("preservation_index")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("PubicBone")
                        .HasColumnName("pubic_bone")
                        .HasColumnType("float");

                    b.Property<string>("PubicSymphysis")
                        .HasColumnName("pubic_symphysis")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Robust")
                        .HasColumnName("robust")
                        .HasColumnType("float");

                    b.Property<double?>("SampleNumber")
                        .HasColumnName("sample_number")
                        .HasColumnType("float");

                    b.Property<double?>("SciaticNotch")
                        .HasColumnName("sciatic_notch")
                        .HasColumnType("float");

                    b.Property<bool>("SoftTissueTaken")
                        .HasColumnName("soft_tissue_taken")
                        .HasColumnType("bit");

                    b.Property<double?>("SouthToFeet")
                        .HasColumnName("south_to_feet")
                        .HasColumnType("float");

                    b.Property<double?>("SouthToHead")
                        .HasColumnName("south_to_head")
                        .HasColumnType("float");

                    b.Property<double?>("SubpubicAngle")
                        .HasColumnName("subpubic_angle")
                        .HasColumnType("float");

                    b.Property<double?>("SupraorbitalRidges")
                        .HasColumnName("supraorbital_ridges")
                        .HasColumnType("float");

                    b.Property<bool>("TextileTaken")
                        .HasColumnName("textile_taken")
                        .HasColumnType("bit");

                    b.Property<double?>("TibiaLength")
                        .HasColumnName("tibia_length")
                        .HasColumnType("float");

                    b.Property<string>("ToothAttrition")
                        .HasColumnName("tooth_attrition")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ToothEruption")
                        .HasColumnName("tooth_eruption")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("ToothTaken")
                        .HasColumnName("tooth_taken")
                        .HasColumnType("bit");

                    b.Property<double?>("VentralArc")
                        .HasColumnName("ventral_arc")
                        .HasColumnType("float");

                    b.Property<double?>("WestToFeet")
                        .HasColumnName("west_to_feet")
                        .HasColumnType("float");

                    b.Property<double?>("WestToHead")
                        .HasColumnName("west_to_head")
                        .HasColumnType("float");

                    b.Property<string>("YearFound")
                        .HasColumnName("year_found")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("ZygomaticCrest")
                        .HasColumnName("zygomatic_crest")
                        .HasColumnType("float");

                    b.HasKey("BurialId")
                        .HasName("burial_ID");

                    b.ToTable("Main$");
                });

            modelBuilder.Entity("Intex_Remix.Models.Oracle", b =>
                {
                    b.Property<string>("AgeAtDeath")
                        .HasColumnName("age_at_death")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("AgeMethod")
                        .HasColumnName("age_method")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialIcon")
                        .HasColumnName("burial_icon")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialIcon2")
                        .HasColumnName("burial_icon_2")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialId")
                        .HasColumnName("burial_ID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationEw")
                        .HasColumnName("burial_location_EW")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BurialLocationNs")
                        .HasColumnName("burial_location_NS")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("BurialNumber")
                        .HasColumnName("burial_number")
                        .HasColumnType("float");

                    b.Property<string>("BurialSubplot")
                        .HasColumnName("burial_subplot")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Depth")
                        .HasColumnName("depth")
                        .HasColumnType("float");

                    b.Property<double?>("Gamous")
                        .HasColumnName("gamous")
                        .HasColumnType("float");

                    b.Property<string>("HairColor")
                        .HasColumnName("hair_color")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("LowPairEw")
                        .HasColumnName("low_pair_EW")
                        .HasColumnType("float");

                    b.Property<double?>("LowPairNs")
                        .HasColumnName("low_pair_NS")
                        .HasColumnType("float");

                    b.Property<string>("Preservation")
                        .HasColumnName("preservation")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Sample")
                        .HasColumnName("sample")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SexMethod")
                        .HasColumnName("sex_method")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("SouthToFeet")
                        .HasColumnName("south_to_feet")
                        .HasColumnType("float");

                    b.Property<double?>("SouthToHead")
                        .HasColumnName("south_to_head")
                        .HasColumnType("float");

                    b.Property<double?>("WestToFeet")
                        .HasColumnName("west_to_feet")
                        .HasColumnType("float");

                    b.Property<double?>("WestToHead")
                        .HasColumnName("west_to_head")
                        .HasColumnType("float");

                    b.ToTable("Oracle$");
                });
#pragma warning restore 612, 618
        }
    }
}
